defaults:
  - agent_quickstart_1
  - override benchmark: futurex
  - _self_

main_agent:
  llm:
    model_name: ${oc.env:OPENAI_MODEL_NAME,qwen/qwen3-next-80b-a3b-thinking}
    openrouter_provider: ${oc.env:OPENAI_PROVIDER,""}

sub_agents:
  agent-worker:
    llm:
      model_name: ${oc.env:WORKER_MODEL_NAME,qwen/qwen3-next-80b-a3b-thinking}
      openrouter_provider: ${oc.env:WORKER_PROVIDER,""}

output_dir: ${oc.env:OUTPUT_DIR,logs/futurex_single_run}
data_dir: ${oc.env:DATA_DIR,data}
